name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clonar SNK modificado
        uses: actions/checkout@v4
        with:
          repository: jjceron/snk
          ref: feature/year-range
          path: .github/actions/snk-custom

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar y Compilar Acción
        run: |
          cd .github/actions/snk-custom
          yarn install --frozen-lockfile
          yarn build

      - name: Generar Snake Animado
        uses: ./.github/actions/snk-custom/packages/action
        with:
          github_user_name: jjceron
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          year: 2025

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}